# Introduction to Tensors

In [2]:
import tensorflow as tf
import numpy as np

2023-03-02 11:47:09.718060: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX512_VNNI
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


**Tensors** are the basic data structure of TensorFlow. They are similar to NumPy's ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.
They are multi-dimensional arrays with a uniform type (called a dtype). They are immutable (can't be changed after they are created).
You can see all the supported dtypes `tf.dtypes.DType`.

## Basics
First, create some basic tensors:
Here is a "scalar" or "rank 0" tensor. It has no axis or dimensions, and only a single value: 

In [3]:
# This will be an int32 tensor by default, see `dtypes` for more info
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


2023-03-02 11:47:13.379536: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX512_VNNI
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-02 11:47:13.380943: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 


A "vector" or "rank 1" tensor. It has one axis, and is a list of values:

In [4]:
# Let's make this a float tensor explicitly
rank_1_tensor = tf.constant([2.0, 3.0, 4.0], dtype=tf.float16)
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float16)


A "matrix" or "rank 2" tensor. It has two axes, and is a list of lists of values:

In [5]:
# Create a rank 2 tensor (a matrix)
rank_2_tensor = tf.constant([[1, 2],
                            [3, 4],
                            [5, 6]])
print(rank_2_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


Tensors can have any number of dimensions. Here is a "rank 3" tensor:

In [6]:
rank_3_tensor = tf.constant(
    [[[0, 1, 2, 3, 4],
      [5, 6, 7, 8, 9]],
      [[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]],
       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


You can convert a tensor to a NumPy array either using np.array or the tensor.numpy method. Tensors and NumPy arrays can be converted to each other. The conversion typically involves copying the underlying data. However, if the dtype and the shape match, the conversion is typically cheap.

In [7]:
np.array(rank_2_tensor)

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [8]:
rank_2_tensor.numpy()

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

On the other hand, you can create a tensor from anything that can be converted to a Tensor using tf.convert_to_tensor:

In [9]:
tf.convert_to_tensor(np.array([[1, 2],[3, 4],[5, 6]]))


<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

You can do basic math on tensors, and the results are tensors:

In [10]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]])

print('Summation: ', a + b) # or tf.add(a, b)
print('Subtraction: ', a - b) # or tf.subtract(a, b)
print('Matrix Multiplication: ', a @ b) # or tf.matmul(a, b)
print('Dot Product: ', tf.tensordot(a, b, axes=1)) # or tf.reduce_sum(a * b, axis=1)
print('Element-wise multiplication: ', a * b) # or tf.multiply(a, b)
print('Element-wise division: ', a / b) # or tf.divide(a, b)
print('Element-wise exponentiation: ', a ** 5) # or tf.pow(a, 5)
print('Element-wise square root: ', tf.sqrt(tf.cast(a, dtype=tf.float64))) # or tf.pow(a, 0.5)

Summation:  tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
Subtraction:  tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int32)
Matrix Multiplication:  tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)
Dot Product:  tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)
Element-wise multiplication:  tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Element-wise division:  tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float64)
Element-wise exponentiation:  tf.Tensor(
[[   1   32]
 [ 243 1024]], shape=(2, 2), dtype=int32)
Element-wise square root:  tf.Tensor(
[[1.         1.41421356]
 [1.73205081 2.        ]], shape=(2, 2), dtype=float64)


Tensors are used in all kinds of operations in TensorFlow:

In [11]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.math.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


## About shapes
A tensor's shape is the number of elements in each dimension. The i-th element of the shape tuple is the length of the tensor along the i-th dimension.
The length of the shape tuple, i.e., the number of tensor axes, is the tensor's rank, or number of dimensions. 
The size of a tensor is the total number of scalars it contains. This is the product of the elements of the shape tuple.

TensorFlow automatically infers shapes during graph construction. These inferred shapes might have known or unknown rank. If the rank is known, the sizes of each dimension might be known or unknown.

Tensors and `tf.TensorShape` objects have a `shape` property that returns a `TensorShape` object. This object can be used to query the rank and dimensions of the tensor. If the rank is known, the dimensions are also known. If the rank is unknown, the dimensions are unknown.

In [12]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

print('Type of every element:', rank_4_tensor.dtype)
print('Number of dimensions (rank):', rank_4_tensor.ndim)
print('Shape of tensor:', rank_4_tensor.shape)
print('Elements along axis 0 of tensor:', rank_4_tensor.shape[0])
print('Elements along the last axis of tensor:', rank_4_tensor.shape[-1])
print('Total number of elements (3*2*4*5): ', tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


But note that the `Tensor.ndim` and `Tensor.shape` attributes don't return Tensor objects. If you need a Tensor use the `tf.rank` or `tf.shape` function. This difference is subtle, but it can be important when building graphs (later).

In [13]:
print(tf.rank(rank_4_tensor))
print(tf.shape(rank_4_tensor))

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([3 2 4 5], shape=(4,), dtype=int32)


While axes are often referred to by their indices, you should always keep track of the meaning of each. Often axes are ordered from global to local: the **batch axis** first, followed by **spatial dimensions**, and **features for each location** last. This way feature vectors are contiguous regions of memory.

Tensors often contain floats, but can also contain many other types such as booleans or strings.
The base tf.Tensor class requires tensors to be *"rectangular"*, meaning that all the "rows" must have the same length. However, there are subclasses of tf.Tensor that allow for more flexible shapes. For example, `tf.SparseTensor` allows for sparse tensors that only store non-zero values and their indices, and `tf.RaggedTensor` allows for tensors with ragged dimensions (ragged dimensions are dimensions where all the slices along the dimension don't have the same size).

## Indexing
### Single-axis indexing
Tensors can be indexed just like Python lists or NumPy arrays:

In [14]:
rank_1_tensor = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [15]:
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())

print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

First: 1
Second: 2
Last: 10
Everything: [ 1  2  3  4  5  6  7  8  9 10]
Before 4: [1 2 3 4]
From 4 to the end: [ 5  6  7  8  9 10]
From 2, before 7: [3 4 5 6 7]
Every other item: [1 3 5 7 9]
Reversed: [10  9  8  7  6  5  4  3  2  1]


### Multi-axis indexing
You can index multiple axes at once, using a comma-separated list of indices or slices:

In [16]:
rank_2_tensor = tf.constant([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                             [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
                             [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [17]:
# Pull out a single value from a 2-rank tensor
print(rank_2_tensor[1, 1].numpy())

# Pull out a submatrix from a 2-rank tensor
print(rank_2_tensor[1:, :].numpy())

# Pull out a single column from a 2-rank tensor
print(rank_2_tensor[:, 2].numpy())

# Skip every other row
print(rank_2_tensor[::2, :].numpy())

12
[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[ 3 13 23]
[[ 1  2  3  4  5  6  7  8  9 10]
 [21 22 23 24 25 26 27 28 29 30]]


## Manipulating shapes
Reshaping is the process of changing the number of rows and columns in a tensor. You can use the `tf.reshape` function to do this. For example, here is a 3x2 tensor:

In [18]:
x = tf.constant([[1, 2],[3, 4],[5, 6]])
print(x)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [19]:
# You can convert the shape to a list with the `as_list` method:
print(x.shape.as_list())

[3, 2]


You can reshape a tensor into a new shape. The `tf.reshape` operation is fast and cheap, since it doesn't require copying any data. However, since it only rearranges the existing data, the new tensor must have the same number of elements as the original tensor. 
The data maintains its layout in memory and a new tensor is created, with the requested shape, pointing to the same data. TensorFlow uses C-style "row-major" memory ordering, where incrementing the rightmost index corresponds to a single step in memory.

Thus, the following code will fail:

In [20]:
# You can reshape a tensor to a new shape. Note that you're passing in a list
reshaped = tf.reshape(x, [2, 3])
print(reshaped)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


If you flatten a tensor you can see what order it is laid out in memory.

In [21]:
# A "-1" in the shape means "whatever fits". The effect is the same as if flattened
print("Original:", x)
print("Reshaped:", tf.reshape(x, [-1]))

Original: tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Reshaped: tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


The data **maintains its layout** in memory and **a new tensor** is created, with the **requested shape**, pointing to the same data. TensorFlow uses C-style "row-major" memory ordering, where incrementing the rightmost index corresponds to a single step in memory.


Typically the only reasonable use of tf.reshape is to combine or split adjacent axes (or add/remove 1s).

For this 3x2x5 tensor, reshaping to (3x2)x5 or 3x(2x5) are both reasonable things to do, as the slices do not mix:

In [25]:
print("Original", rank_3_tensor)
print("\nReshaped", tf.reshape(rank_3_tensor, [3*2, 5]))
print("\nReshaped", tf.reshape(rank_3_tensor, [3, 2*5]))
print("\nReshaped", tf.reshape(rank_3_tensor, [3, -1]))

Original tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)

Reshaped tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)

Reshaped tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)

Reshaped tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


Reshaping will "work" for any new shape with the same total number of elements, but it will not do anything useful if you do not respect the order of the axes.

Swapping axes in tf.reshape does not work; you need tf.transpose for that.

In [24]:
# Bad examples: don't do this

# You can't reorder axes with reshape.
print(tf.reshape(rank_3_tensor, [2, 3, 5]), "\n") 

# This is a mess
print(tf.reshape(rank_3_tensor, [5, 6]), "\n")

# This doesn't work at all
try:
  tf.reshape(rank_3_tensor, [7, -1])
except Exception as e:
  print(f"{type(e).__name__}: {e}")

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]], shape=(2, 3, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]], shape=(5, 6), dtype=int32) 

InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 30 values, but the requested shape requires a multiple of 7 [Op:Reshape]


If you want to reorder the axes, you can use `tf.transpose`. It takes a tensor and a permutation of the dimensions. The returned tensor has the same values as the input, but its axes are permuted in the order specified by the permutation argument.

In [39]:
print("Original:", rank_3_tensor)
print("\nTransposed:", tf.transpose(rank_3_tensor, perm=[1, 0, 2]))
print("\nTransposed:", tf.transpose(rank_3_tensor, perm=[2, 1, 0]))

Original: tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)

Transposed: tf.Tensor(
[[[ 0  1  2  3  4]
  [10 11 12 13 14]
  [20 21 22 23 24]]

 [[ 5  6  7  8  9]
  [15 16 17 18 19]
  [25 26 27 28 29]]], shape=(2, 3, 5), dtype=int32)

Transposed: tf.Tensor(
[[[ 0 10 20]
  [ 5 15 25]]

 [[ 1 11 21]
  [ 6 16 26]]

 [[ 2 12 22]
  [ 7 17 27]]

 [[ 3 13 23]
  [ 8 18 28]]

 [[ 4 14 24]
  [ 9 19 29]]], shape=(5, 2, 3), dtype=int32)


You can use the `tf.squeeze` function to remove dimensions of size 1, and the `tf.expand_dims` function to add dimensions of size 1. For example, here is a 3x1x2x1 tensor:

In [40]:
tensor_3121 = tf.constant([0,1,2,3,4,5], shape=(3, 1, 2 , 1))
print("Original:", tensor_3121)
print("\nSqueezed:", tf.squeeze(tensor_3121))
print("\nExpanded:", tf.expand_dims(tensor_3121, axis=0))


Original: tf.Tensor(
[[[[0]
   [1]]]


 [[[2]
   [3]]]


 [[[4]
   [5]]]], shape=(3, 1, 2, 1), dtype=int32)

Squeezed: tf.Tensor(
[[0 1]
 [2 3]
 [4 5]], shape=(3, 2), dtype=int32)

Expanded: tf.Tensor(
[[[[[0]
    [1]]]


  [[[2]
    [3]]]


  [[[4]
    [5]]]]], shape=(1, 3, 1, 2, 1), dtype=int32)


You may run across not-fully-specified shapes. Either the shape contains a None (an axis-length is unknown) or the whole shape is None (the rank of the tensor is unknown).

Except for `tf.RaggedTensor`, such shapes will only occur in the context of TensorFlow's symbolic, graph-building APIs:

* tf.function
* The keras functional API.

## More on DTypes
A tf.Tensor has a datatype (called a tf.DType).
To inspect a `tf.Tensor`'s data type use the `Tensor.dtype` property.

When creating a `tf.Tensor` from a Python object you may optionally specify the datatype.

If you don't, TensorFlow chooses a datatype that can represent your data. TensorFlow converts Python integers to `tf.int32` and Python floating point numbers to `tf.float32`. Otherwise TensorFlow uses the same rules NumPy uses when converting to arrays, as described in the [NumPy dtypes documentation](https://numpy.org/doc/stable/user/basics.types.html).

You can explicitly convert a `tf.Tensor` from one datatype to another using `Tensor.cast`.

In [32]:
the_f64_tensor = tf.constant([1.1, 2.2, 3.3], dtype=tf.float64)
print("f64:", the_f64_tensor)

the_f32_tensor = tf.cast(the_f64_tensor, dtype=tf.float32)
print("f32", the_f32_tensor)

# Loss of precision
print("f64 as uint8:", tf.cast(the_f64_tensor, dtype=tf.uint8))

# You can also cast a NumPy array or a Python list
the_f16_tensor = tf.cast(np.array([1.1, 2.2, 3.3]), dtype=tf.float16)
print("From np.array:", the_f16_tensor)

f64: tf.Tensor([1.1 2.2 3.3], shape=(3,), dtype=float64)
f32 tf.Tensor([1.1 2.2 3.3], shape=(3,), dtype=float32)
f64 as uint8: tf.Tensor([1 2 3], shape=(3,), dtype=uint8)
From np.array: tf.Tensor([1.1 2.2 3.3], shape=(3,), dtype=float16)


## Broadcasting

Broadcasting is a powerful mechanism that allows TensorFlow to work with tensors of different shapes when performing arithmetic operations. The term broadcasting was first used by [Numpy](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

In short, under certain conditions, smaller tensors are "stretched" automatically to fit larger tensors when running combined operations on them.
The simplest and most common case is when you attempt to multiply or add a tensor to a scalar. In that case, the scalar is broadcast to be the same shape as the other argument.

In [42]:
x = tf.constant([1, 2, 3])

y = tf.constant(2)
z = tf.constant([2, 2, 2])

# Element-wise addition, all produce the same result
print('x + 2 = ', x + 2)
print('x + y = ', x + y)
print('x + z = ', x + z)

x + 2 =  tf.Tensor([3 4 5], shape=(3,), dtype=int32)
x + y =  tf.Tensor([3 4 5], shape=(3,), dtype=int32)
x + z =  tf.Tensor([3 4 5], shape=(3,), dtype=int32)


Likewise, axes with length 1 can be stretched out to match the other arguments. Both arguments can be stretched in the same computation.

In this case a 3x1 matrix is element-wise multiplied by a 1x4 matrix to produce a 3x4 matrix. Note how the leading 1 is optional: The shape of y is [4].

In [45]:
x = tf.reshape(x, (3, 1))
y = tf.range(1, 5) # this is actually a vector, a tensor with a single dimension (4,) that will be stretched

# element-wise multiplication
print(x, '\n')
print(y, '\n')
print(tf.multiply(x, y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [46]:
# Which is equivalent to
x_stretched = tf.constant([[1, 1, 1, 1],
                           [2, 2, 2, 2],
                           [3, 3, 3, 3]])

y_stretched = tf.constant([[1, 2, 3, 4],
                           [1, 2, 3, 4],
                           [1, 2, 3, 4]])

print(x_stretched, '\n')
print(y_stretched, '\n')

print(x_stretched * y_stretched) # element-wise multiplication, operator overloading

tf.Tensor(
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]], shape=(3, 4), dtype=int32) 

tf.Tensor(
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]], shape=(3, 4), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


Most of the time, broadcasting is both time and space efficient, as the broadcast operation **never materializes the expanded tensors in memory**.

You see what broadcasting looks like using `tf.broadcast_to`.

In [47]:
print(tf.broadcast_to(tf.constant([1, 2, 3]), shape=(3, 3)))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


Unlike a mathematical op, for example, broadcast_to does nothing special to save memory. Here, you are materializing the tensor.

## tf.convert_to_tensor

Most ops, like `tf.matmul` and `tf.reshape` take arguments of class tf.Tensor. However, you'll notice in the above case, Python objects shaped like tensors are accepted.

Most, but not all, ops call convert_to_tensor on non-tensor arguments. There is a registry of conversions, and most object classes like NumPy's ndarray, TensorShape, Python lists, and tf.Variable will all convert automatically.

See `tf.register_tensor_conversion_function` for more details, and if you have your own type you'd like to automatically convert to a tensor.

## Ragged Tensor

A tensor with variable numbers of elements along one axis is called "ragged". Use `tf.RaggedTensor` to represent them.
You can create a `tf.RaggedTensor` from a nested Python list of values.

In [49]:
ragged_list = [[1, 2], [3, 4, 5], [6], [], [7]]
print(ragged_list)

try:
    tensor = tf.constant(ragged_list)
except Exception as e:
    print(f"{type(e).__name__}: {e}")

ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)
print(ragged_tensor.shape)

[[1, 2], [3, 4, 5], [6], [], [7]]
ValueError: Can't convert non-rectangular Python sequence to Tensor.
<tf.RaggedTensor [[1, 2], [3, 4, 5], [6], [], [7]]>
(5, None)


## String Tensors

`tf.string` is a dtype, which is to say you can represent data as strings (variable-length byte arrays) in tensors.

The strings are atomic and cannot be indexed the way Python strings are. The length of the string is not one of the axes of the tensor. See `tf.strings` for functions to manipulate them.

Here is a scalar string tensor:

In [51]:
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)

tensor_of_strings = tf.constant(["Gray wolf",
                             "Quick brown fox",
                             "Lazy dog"])
print(tensor_of_strings) # it is a vector of strings, and the shape is (3,)

tf.Tensor(b'Gray wolf', shape=(), dtype=string)
tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)


In the above printout the b prefix indicates that tf.string dtype is not a unicode string, but a byte-string. See the [Unicode Tutorial](https://www.tensorflow.org/tutorials/load_data/unicode) for more about working with unicode text in TensorFlow.

If you pass unicode characters they are utf-8 encoded.

In [52]:
tf.constant("🥳👍")

<tf.Tensor: shape=(), dtype=string, numpy=b'\xf0\x9f\xa5\xb3\xf0\x9f\x91\x8d'>

Some basic functions are available in `tf.strings`:

In [78]:
print(tf.strings.length(scalar_string_tensor))
print(tf.strings.length(tensor_of_strings, unit="UTF8_CHAR"))

# Decode the string into a vector of Unicode code points
print(tf.strings.unicode_decode(scalar_string_tensor, "UTF-8"))

# Split a string into a vector of strings
print(tf.strings.split(scalar_string_tensor, sep=" "))
print(tf.strings.split(tensor_of_strings, sep=" ")) # returns a ragged tensor

# Get the first 5 characters
print(tf.strings.substr(scalar_string_tensor, pos=0, len=5))

# Convert to numbers
numbers = tf.constant('1 10 100')
print(tf.strings.to_number(tf.strings.split(numbers, sep=' '), out_type=tf.int32))

# Convert to bytes
byte_strings = tf.strings.bytes_split(tf.strings.split(numbers, sep=' '))
print(byte_strings)
byte_ints = tf.io.decode_raw(tf.constant('1 10 100'), tf.uint8)
print(byte_ints)

# Split as unicode code points and then decode it
unicode_bytes = tf.constant(['🥳', '👍']) # a vector of byte-strings
print(unicode_bytes)
unicode_char_bytes = tf.strings.unicode_split(unicode_bytes, input_encoding='UTF-8')
print(unicode_char_bytes)
unicode_chars = tf.strings.unicode_decode(unicode_bytes, input_encoding='UTF-8')
print(unicode_chars)

tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor([ 9 15  8], shape=(3,), dtype=int32)
tf.Tensor([ 71 114  97 121  32 119 111 108 102], shape=(9,), dtype=int32)
tf.Tensor([b'Gray' b'wolf'], shape=(2,), dtype=string)
<tf.RaggedTensor [[b'Gray', b'wolf'], [b'Quick', b'brown', b'fox'], [b'Lazy', b'dog']]>
tf.Tensor(b'Gray ', shape=(), dtype=string)
tf.Tensor([  1  10 100], shape=(3,), dtype=int32)
<tf.RaggedTensor [[b'1'], [b'1', b'0'], [b'1', b'0', b'0']]>
tf.Tensor([49 32 49 48 32 49 48 48], shape=(8,), dtype=uint8)
tf.Tensor([b'\xf0\x9f\xa5\xb3' b'\xf0\x9f\x91\x8d'], shape=(2,), dtype=string)
<tf.RaggedTensor [[b'\xf0\x9f\xa5\xb3'],
 [b'\xf0\x9f\x91\x8d']]>
<tf.RaggedTensor [[129395],
 [128077]]>


The `tf.string` dtype is used for all raw bytes data in TensorFlow. The `tf.io` module contains functions for converting data to and from bytes, including decoding images and parsing csv.

## Sparse Tensors
A `tf.SparseTensor` represents a set of sparse indices and a corresponding array of values. The tensor is dense if all values are specified, but it is sparse if only a subset of values are specified.

In [81]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 1], [1, 0], [2, 3]],
                                       values=[1., 2., 3.],
                                       dense_shape=[3, 4])

print(sparse_tensor, '\n')

# Convert to dense tensor
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[0. 1. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 3.]], shape=(3, 4), dtype=float32)
